/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 ./public/models/cars/ae86/scene.gltf 
Author: DAS AUTO (https://sketchfab.com/das_auto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-ae86-hachiroku-79878c7477f941a4ac4bb16c239bab9f
Title: Toyota AE86 Hachiroku
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function AE86(props) {
  const { nodes, materials } = useGLTF("/models/cars/ae86/scene.gltf");
  return (
    <group {...props} dispose={null} scale={2} castShadow receiveShadow>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.INT_rubber}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.EXT_brakes}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Tyre}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.EXT_rim}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.EXT_details}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.EXT_SUPPORTS}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.SUSP_black}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.EXT_body_lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.EXT_lights_indicator_glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.EXT_Headlights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.EXT_lights_int}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.plate_1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.EXT_body_panda}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.EXT_body}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.EXT_body_hood}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.EXT_underside}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.EXT_details_oldae}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.EXT_exhaust}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.EXT_lights}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.plate_holder}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.EXT_body_panda_r_bamp}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.EXT_trueno_kouki}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.EXT_body_panda_kouki}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.EXT_lights_glass_no2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.SUSP_green}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials["P-AE_COLOR2"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.WCEXTRA1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.FUEL_INDICATOR}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.Gauge_strelka}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.INT_details_AT}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.Monitor_black}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.Monitor_LED}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.Material_626}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.INT_body}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.EXT_stoika_black}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.SUSP_grey}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_76.geometry}
        material={materials.INT_body_panda}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.INT_leather}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials.INT_plastic}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.INT_plastic_color}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.INT_details_PLASTIC}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.EXT_mirror}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_88.geometry}
        material={materials.EXT_lights_glass_no}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.EXT_glass}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials.EXT_body_panda_f_bamp}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.EXT_trueno}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.EXT_lights_2}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.EXT_REAR_LIGHTS_CHROME}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.EXT_kouki_plastik}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_102.geometry}
        material={materials.EXT_kouki_trans}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials.EXT_kouki_no_trans}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials.Material_1722}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.Material_625}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.INT_CintureSicurezza}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials.INT_Decal_Metal}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.Gauge_bbg}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials.Gauge_decal}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials.Gauge_plastik}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials.Gauge_steklo}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_122.geometry}
        material={materials.INT_belts}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_124.geometry}
        material={materials.INT_details_METAL}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_126.geometry}
        material={materials.INT_Seat_fabric_side}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_128.geometry}
        material={materials.INT_Plastic_Grey}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_130.geometry}
        material={materials.INT_Carbon}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_132.geometry}
        material={materials.INT_Seat_fabric}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_134.geometry}
        material={materials.INT_Decal_Metal_Alfa}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials.INT_Decal_Alfa}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials.INT_Skinned_Gearshift}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_140.geometry}
        material={materials.INT_leather_SW}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.INT_details_SW_metal}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials.INT_seam}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials.INT_fabric}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials.INT_fabric_floor}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_150.geometry}
        material={materials.INT_fabric_color}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_152.geometry}
        material={materials.INT_DETAILS_OPAQUE}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/cars/ae86/scene.gltf");
