/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export default function Fox(props) {
  const group = useRef();

  const fox = useGLTF("/Fox.gltf");
  const animations = useAnimations(fox.animations, fox.scene);

  const { animationName } = useControls({
    animationName: { options: animations.names },
  });

  useEffect(() => {
    const action = animations.actions[animationName];
    action.reset().fadeIn(0.5).play();

    console.log(animationName);

    return () => {
      action.fadeOut(0.5);
    };
  }, [animationName]);

  return (
    <primitive
      object={fox.scene}
      scale={0.02}
      position={[-2.5, 0, 2.5]}
      rotation-y={0.3}
    />
  );

  // return (
  //   <group ref={group} {...props} dispose={null}>
  //     <group>
  //       <group name="root">
  //         <skinnedMesh
  //           name="fox"
  //           geometry={fox.nodes.fox.geometry}
  //           material={fox.materials.fox_material}
  //           skeleton={fox.nodes.fox.skeleton}
  //         />
  //         <primitive object={fox.nodes._rootJoint} />
  //       </group>
  //     </group>
  //   </group>
  // );
}

useGLTF.preload("/Fox.gltf");
