/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export default function Fox(props) {
  const group = useRef();

  const fox = useGLTF("/Fox.gltf");
  const animations = useAnimations(fox.animations, fox.scene);

  const { animationName } = useControls({
    animationName: { options: animations.names },
  });

  // useEffect(() => {
  //   actions.Survey.play();

  //   window.setTimeout(() => {
  //     actions.Walk.play();
  //     actions.Walk.crossFadeFrom(actions.Survey, 2);
  //   }, 2000);

  //   window.setTimeout(() => {
  //     actions.Run.play();
  //     actions.Run.crossFadeFrom(actions.Walk, 2);
  //   }, 4000);
  // }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="root">
          <skinnedMesh
            name="fox"
            geometry={fox.nodes.fox.geometry}
            material={fox.materials.fox_material}
            skeleton={fox.nodes.fox.skeleton}
          />
          <primitive object={fox.nodes._rootJoint} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Fox.gltf");
